addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - imagemagick
    
before_script:
 - chmod +x .travis/push.sh
 
script:
  - pdflatex cv.tex
  
after_success:
  - convert -density 300 cv.pdf -quality 100 cv.png
  - .travis/push.sh
