#language: node_js

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra

script:
  - pdflatex cv.tex
#after_script:
#  - docker-compose kill
